// Camada 3 — Motor Web3: gera o código-fonte de um contrato Solidity
// (ERC-20 por padrão, baseado em OpenZeppelin) a partir de parâmetros
// validados. Não compila nem deploya — devolve o .sol pronto para
// download / commit no GitHub. A compilação/deploy fica para a próxima
// iteração para manter a edge function leve e rápida.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
}

type Body = {
  plan_id?: string
  name: string
  symbol: string
  decimals?: number
  initial_supply?: string | number
  standard?: 'erc20'
  solidity_version?: string
}

/** Valida identificador Solidity (PascalCase, sem espaços nem reservadas). */
const SOL_IDENT = /^[A-Z][A-Za-z0-9_]{1,40}$/
const SYMBOL = /^[A-Z0-9]{2,11}$/
const VERSION = /^0\.8\.\d{1,2}$/

function buildErc20Source(p: Required<Pick<Body, 'name' | 'symbol' | 'decimals' | 'solidity_version'>> & { initial_supply: string }): string {
  // OpenZeppelin v5.x — Ownable exige initialOwner no construtor.
  return `// SPDX-License-Identifier: MIT
// Generated by Kubo Vibe Dev — Camada 3 (Web3 Engine)
pragma solidity ^${p.solidity_version};

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

contract ${p.name} is ERC20, Ownable {
    uint8 private immutable _customDecimals;

    constructor(address initialOwner)
        ERC20(${JSON.stringify(p.name)}, ${JSON.stringify(p.symbol)})
        Ownable(initialOwner)
    {
        _customDecimals = ${p.decimals};
        if (${p.initial_supply} > 0) {
            _mint(initialOwner, ${p.initial_supply} * (10 ** uint256(_customDecimals)));
        }
    }

    function decimals() public view virtual override returns (uint8) {
        return _customDecimals;
    }

    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }

    function burn(uint256 amount) external {
        _burn(msg.sender, amount);
    }
}
`
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders })

  try {
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
    const SUPABASE_ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!
    const authHeader = req.headers.get('Authorization') ?? ''
    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: authHeader } },
    })
    const { data: userData, error: userErr } = await supabase.auth.getUser()
    if (userErr || !userData.user) {
      return new Response(JSON.stringify({ error: 'unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const body = (await req.json().catch(() => ({}))) as Body
    const standard = body.standard ?? 'erc20'
    if (standard !== 'erc20') {
      return new Response(JSON.stringify({ error: 'only erc20 supported in MVP' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }
    const name = String(body.name ?? '').trim()
    const symbol = String(body.symbol ?? '').trim().toUpperCase()
    const decimals = Number.isFinite(body.decimals) ? Number(body.decimals) : 18
    const initialSupply = String(body.initial_supply ?? '0').trim()
    const solidity = String(body.solidity_version ?? '0.8.24')

    if (!SOL_IDENT.test(name)) return badRequest('name must match ' + SOL_IDENT)
    if (!SYMBOL.test(symbol)) return badRequest('symbol must match ' + SYMBOL)
    if (!Number.isInteger(decimals) || decimals < 0 || decimals > 36) return badRequest('decimals 0..36')
    if (!/^\d{1,30}$/.test(initialSupply)) return badRequest('initial_supply must be a non-negative integer string')
    if (!VERSION.test(solidity)) return badRequest('solidity_version must match ' + VERSION)

    const source_code = buildErc20Source({
      name, symbol, decimals,
      initial_supply: initialSupply,
      solidity_version: solidity,
    })

    // Verifica que plan_id (se enviado) pertence ao usuário (RLS já garante,
    // mas damos uma mensagem de erro clara em vez de violar RLS).
    let planId: string | null = null
    if (body.plan_id) {
      const { data: plan } = await supabase
        .from('orchestration_plans')
        .select('id').eq('id', body.plan_id).maybeSingle()
      if (!plan) return badRequest('plan_id not found or not yours')
      planId = plan.id
    }

    const { data: saved, error: insertErr } = await supabase
      .from('generated_contracts')
      .insert({
        user_id: userData.user.id,
        plan_id: planId,
        standard,
        name, symbol, decimals,
        initial_supply: initialSupply,
        source_code,
        solidity_version: solidity,
        metadata: { openzeppelin: '^5.0.0' },
      })
      .select('id, created_at')
      .single()

    if (insertErr) {
      console.error('insert failed', insertErr)
      return new Response(JSON.stringify({ error: 'persist_failed' }), {
        status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    return new Response(
      JSON.stringify({
        contract_id: saved.id,
        created_at: saved.created_at,
        standard, name, symbol, decimals,
        initial_supply: initialSupply,
        solidity_version: solidity,
        source_code,
        filename: `${name}.sol`,
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } },
    )
  } catch (e) {
    console.error('web3-contract-gen error', e)
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : 'unknown' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})

function badRequest(msg: string): Response {
  return new Response(JSON.stringify({ error: msg }), {
    status: 400,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers':
        'authorization, x-client-info, apikey, content-type',
    },
  })
}
