// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's KUBO Vibe projects, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many projects to return."),
    publishedOnly: z.boolean().default(false).describe("Only return published projects.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, publishedOnly }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id,title,description,is_published,published_url,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (publishedOnly) query = query.eq("is_published", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch one of the signed-in user's projects by id, optionally including its generated code.",
  inputSchema: {
    projectId: z2.string().uuid().describe("The project id."),
    includeCode: z2.boolean().default(false).describe("Include the generated source code.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ projectId, includeCode }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const columns = includeCode ? "id,title,description,is_published,published_url,created_at,updated_at,generated_code" : "id,title,description,is_published,published_url,created_at,updated_at";
    const { data, error } = await supabase.from("projects").select(columns).eq("id", projectId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Project not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/create-project.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_project_default = defineTool3({
  name: "create_project",
  title: "Create project",
  description: "Create a new KUBO Vibe project for the signed-in user.",
  inputSchema: {
    title: z3.string().trim().min(1).max(120).describe("Project title."),
    description: z3.string().trim().max(500).optional().describe("Optional short description.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").insert({ user_id: ctx.getUserId(), title, description: description ?? null }).select("id,title,description,created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-agent-jobs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_agent_jobs_default = defineTool4({
  name: "list_agent_jobs",
  title: "List agent jobs",
  description: "List the signed-in user's recent AI agent jobs with status, credits charged and errors.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(10).describe("How many jobs to return."),
    status: z4.string().trim().min(1).optional().describe("Filter by status, e.g. pending, running, completed, failed."),
    agentSlug: z4.string().trim().min(1).optional().describe("Filter by agent slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, agentSlug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("agent_jobs").select(
      "id,agent_slug,status,credits_charged,duration_ms,error_message,created_at,completed_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (agentSlug) query = query.eq("agent_slug", agentSlug);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/credit-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var credit_summary_default = defineTool5({
  name: "credit_summary",
  title: "Credit summary",
  description: "Return the signed-in user's latest credit balance and their most recent credit transactions.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10).describe("How many transactions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("credit_transactions").select("id,delta,balance_after,category,reason,created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const transactions = data ?? [];
    const balance = transactions[0]?.balance_after ?? null;
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ balance, transactions }, null, 2)
        }
      ],
      structuredContent: { balance, transactions }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dlqmmubasyldcylhnqqd";
var mcp_default = defineMcp({
  name: "kubo-vibe-dev",
  title: "KUBO VIBE DEV",
  version: "0.1.0",
  instructions: "Tools for KUBO VIBE DEV, an AI platform for generating web and Web3 apps. Use `list_projects` and `get_project` to inspect the user's projects, `create_project` to start a new one, `list_agent_jobs` to check AI agent runs, and `credit_summary` for credit balance and usage. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    create_project_default,
    list_agent_jobs_default,
    credit_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
