
REVOKE EXECUTE ON FUNCTION public.log_security_audit(TEXT, TEXT, TEXT, TEXT, TEXT, INET, TEXT, BOOLEAN, TEXT, JSONB, UUID, TEXT) FROM authenticated, anon, PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_security_audit(TEXT, TEXT, TEXT, TEXT, TEXT, INET, TEXT, BOOLEAN, TEXT, JSONB, UUID, TEXT) TO service_role;
